## The first function, `makeCacheMatrix` creates a special "matrix", which is
## a list containing four functions to set and get the value of the matrix, 
## and to set and get the value of its inverse.

makeCacheMatrix <- function(x = matrix()) {
    inv<-NULL
    set<-function(y){
        x<<-y
        inv<<-NULL
    }
    get<-function() x
    setInverse<-function(inverse)inv<<-inverse
    getInverse<-function() inv
    list(set = set, get = get,setInverse = setInverse,
         getInverse = getInverse)
}


## The second function will take a "matrix" generated by the first function 
## "makeCacheMatrix" as its input. Then, it will check if the matrix's inverse
## has been calculated. If so, it will return the stored value. If not, it will
## work out the inverse and store it.

cacheSolve <- function(x, ...) {
    inv<-x$getInverse()
    if (!is.null(inv)){
        message("getting cached data")
        return(inv)
    }
    data<-x$get()
    x$setInverse(solve(data,...))
    x$getInverse()
}
